spring.application.name=msGame
server.port=8081


# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/msgame_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=32781
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret
app.rabbitmq.exchange=auth.exchange
app.rabbitmq.queue=player.creation.queue
app.rabbitmq.routing-key=auth.createUser

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect